### ISSUE TITLE
Bot_Freeze.sma Error

### ISSUE THREAD

**Issue by arkprocession** [mlibre2/pawnamxx#1]
The cvar is updated for bot_freeze.sma but not the functionality.
I added everything i had to the prefix de_ maps for example and another config for fy_maps 
i need to make two or more changelevels for it to apply ands its very inconsistent.

Could that be fixed? so i can update the value more dynamically? even changing it manually once the round started doesnt work

I want a value for each map, thats why.

Thanks

**Comment by mlibre2** [comment]
@arkprocession [try](https://github.com/mlibre2/pawnamxx/commit/ecb82fd7d5bf634bc6e0032e2c268402054ac83b) now.

**Comment by arkprocession** [comment]
> @arkprocession [try](https://github.com/mlibre2/pawnamxx/commit/ecb82fd7d5bf634bc6e0032e2c268402054ac83b) now.

Thank you mlibre2, now it works perfectly! Belive it or not this is huge for me. Great QOL! great code and brilliant to actually use bot_freeze native command.

i was trying a lot with many task schedulers but couldn't recreate this.

Are you taking requests for simple but qol things? for example:
a way to add cvars to certain existing plugins to avoid checks on bots so they become less resource intensive.
fixing plugins like: https://forums.alliedmods.net/showthread.php?t=68977 where the probability is broken and is not taking into account percentage of error.
And silly things like that.
let me know.

Thank you for this i will be closing it as resolved :)
